2025-10-09 00:55:22,116 - app - INFO - config:34 - Application startup...
2025-10-09 00:55:22,116 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 00:55:37,879 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-09 00:55:37,989 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-09 00:55:37,989 - app - INFO - config:37 - Application shutdown.
2025-10-09 00:55:37,989 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-09 00:55:37,989 - uvicorn.error - INFO - server:94 - Finished server process [6112]
2025-10-09 00:59:25,395 - app - INFO - config:31 - Application startup...
2025-10-09 00:59:25,396 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 00:59:42,087 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-09 00:59:42,197 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-09 00:59:42,197 - app - INFO - config:33 - Application shutdown.
2025-10-09 00:59:42,197 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-09 00:59:42,197 - uvicorn.error - INFO - server:94 - Finished server process [7832]
2025-10-09 22:30:21,348 - app - INFO - config:31 - Application startup......................................
2025-10-09 22:30:21,348 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 22:32:26,080 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54299 - "POST /login/access-token HTTP/1.1" 200
2025-10-09 23:31:19,736 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54828 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 401
2025-10-09 23:31:58,033 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54849 - "POST /login/access-token HTTP/1.1" 200
2025-10-09 23:32:33,410 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54854 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 401
2025-10-09 23:32:50,403 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54855 - "GET /permission/?skip=0&limit=10 HTTP/1.1" 401
2025-10-09 23:35:45,120 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54889 - "GET /permission/?skip=0&limit=10 HTTP/1.1" 401
2025-10-09 23:35:59,868 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-09 23:35:59,975 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-09 23:35:59,975 - app - INFO - config:33 - Application shutdown.....................................
2025-10-09 23:35:59,975 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-09 23:35:59,975 - uvicorn.error - INFO - server:94 - Finished server process [724]
2025-10-09 23:36:01,147 - app - INFO - config:31 - Application startup......................................
2025-10-09 23:36:01,147 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 23:36:07,664 - app - INFO - config:31 - Application startup......................................
2025-10-09 23:36:07,665 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 23:36:13,982 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54912 - "GET /permission/?skip=0&limit=10 HTTP/1.1" 401
2025-10-09 23:37:05,310 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54934 - "GET /permission/?skip=0&limit=10 HTTP/1.1" 401
2025-10-09 23:37:07,468 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54934 - "GET /permission/?skip=0&limit=10 HTTP/1.1" 401
2025-10-09 23:37:14,881 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54938 - "GET /docs HTTP/1.1" 200
2025-10-09 23:37:14,989 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54938 - "GET /openapi.json HTTP/1.1" 200
2025-10-09 23:37:35,467 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:54939 - "POST /login/access-token HTTP/1.1" 200
2025-10-09 23:38:15,635 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-09 23:38:15,743 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-09 23:38:15,743 - app - INFO - config:33 - Application shutdown.....................................
2025-10-09 23:38:15,744 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-09 23:38:15,744 - uvicorn.error - INFO - server:94 - Finished server process [14816]
2025-10-09 23:41:50,504 - app - INFO - config:31 - Application startup......................................
2025-10-09 23:41:50,504 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 23:41:56,487 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55009 - "GET /docs HTTP/1.1" 200
2025-10-09 23:41:56,663 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55009 - "GET /openapi.json HTTP/1.1" 200
2025-10-09 23:42:13,720 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55010 - "POST /login/access-token HTTP/1.1" 200
2025-10-09 23:42:41,252 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55029 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 200
2025-10-09 23:43:06,444 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55043 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 403
2025-10-09 23:43:27,778 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-09 23:43:27,886 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-09 23:43:27,886 - app - INFO - config:33 - Application shutdown.....................................
2025-10-09 23:43:27,886 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-09 23:43:27,887 - uvicorn.error - INFO - server:94 - Finished server process [7044]
2025-10-09 23:56:06,098 - app - INFO - config:31 - Application startup......................................
2025-10-09 23:56:06,098 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-09 23:56:38,349 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55164 - "GET /docs HTTP/1.1" 200
2025-10-09 23:56:38,523 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55164 - "GET /openapi.json HTTP/1.1" 200
2025-10-09 23:56:58,481 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55165 - "POST /login/access-token HTTP/1.1" 200
2025-10-09 23:57:33,403 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55184 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 500
2025-10-09 23:57:33,404 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\result.py", line 199, in _key_not_found
    self._key_fallback(key, None)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\result.py", line 138, in _key_fallback
    raise KeyError(key) from err
KeyError: 'is_active'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 377, in app
    solved_result = await solve_dependencies(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\dependencies\utils.py", line 646, in solve_dependencies
    solved = await call(**solved_result.values)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\security.py", line 123, in get_current_active_user
    if not current_user.is_active:
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 66, in sqlalchemy.cyextension.resultproxy.BaseRow.__getattr__
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 63, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\result.py", line 201, in _key_not_found
    raise AttributeError(ke.args[0]) from ke
AttributeError: is_active
2025-10-10 00:02:07,564 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 00:02:07,673 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 00:02:07,674 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 00:02:07,674 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 00:02:07,674 - uvicorn.error - INFO - server:94 - Finished server process [9868]
2025-10-10 00:10:39,613 - app - INFO - config:31 - Application startup......................................
2025-10-10 00:10:39,614 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 00:10:55,600 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55298 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 200
2025-10-10 00:11:22,000 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55308 - "GET /docs HTTP/1.1" 200
2025-10-10 00:11:22,169 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55308 - "GET /openapi.json HTTP/1.1" 200
2025-10-10 00:11:27,197 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55309 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 403
2025-10-10 00:11:55,123 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55323 - "POST /login/access-token HTTP/1.1" 200
2025-10-10 00:12:21,845 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55326 - "GET /permission/?skip=0&limit=100 HTTP/1.1" 200
2025-10-10 00:21:27,297 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 00:21:27,408 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 00:21:27,408 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 00:21:27,409 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 00:21:27,409 - uvicorn.error - INFO - server:94 - Finished server process [12168]
2025-10-10 00:30:17,907 - app - INFO - config:31 - Application startup......................................
2025-10-10 00:30:17,907 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 00:30:41,368 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55874 - "GET /user/ HTTP/1.1" 200
2025-10-10 00:31:35,126 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:55946 - "GET /user/ HTTP/1.1" 403
2025-10-10 00:46:39,343 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 00:46:39,451 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 00:46:39,451 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 00:46:39,452 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 00:46:39,452 - uvicorn.error - INFO - server:94 - Finished server process [9136]
2025-10-10 00:46:50,870 - app - INFO - config:31 - Application startup......................................
2025-10-10 00:46:50,870 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 00:47:00,876 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:56077 - "GET /user/ HTTP/1.1" 403
2025-10-10 00:47:19,399 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 00:47:19,507 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 00:47:19,507 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 00:47:19,507 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 00:47:19,507 - uvicorn.error - INFO - server:94 - Finished server process [5420]
2025-10-10 16:46:20,586 - app - INFO - config:31 - Application startup......................................
2025-10-10 16:46:20,586 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 16:46:38,197 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:59640 - "POST /login/access-token HTTP/1.1" 200
2025-10-10 17:08:24,619 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:59989 - "POST /user/ HTTP/1.1" 403
2025-10-10 17:08:41,853 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:59997 - "POST /login/access-token HTTP/1.1" 200
2025-10-10 17:09:07,398 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60009 - "POST /user/ HTTP/1.1" 403
2025-10-10 17:20:29,785 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 17:20:29,893 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 17:20:29,894 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 17:20:29,894 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 17:20:29,894 - uvicorn.error - INFO - server:94 - Finished server process [8424]
2025-10-10 17:21:06,016 - app - INFO - config:31 - Application startup......................................
2025-10-10 17:21:06,016 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 17:21:14,106 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60715 - "GET /docs HTTP/1.1" 200
2025-10-10 17:21:14,309 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60715 - "GET /openapi.json HTTP/1.1" 200
2025-10-10 17:21:46,849 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60716 - "POST /login/access-token HTTP/1.1" 200
2025-10-10 17:23:43,084 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60841 - "POST /user/ HTTP/1.1" 422
2025-10-10 17:25:12,122 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60916 - "POST /user/ HTTP/1.1" 400
2025-10-10 17:25:50,254 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60943 - "POST /user/ HTTP/1.1" 500
2025-10-10 17:25:50,254 - uvicorn.error - ERROR - httptools_impl:414 - Exception in ASGI application
Traceback (most recent call last):
  File "asyncpg\\protocol\\prepared_stmt.pyx", line 175, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg\\protocol\\codecs/base.pyx", line 227, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg\\protocol\\codecs/base.pyx", line 129, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg\\pgproto\\./codecs/text.pyx", line 29, in asyncpg.pgproto.pgproto.text_encode
  File "asyncpg\\pgproto\\./codecs/text.pyx", line 12, in asyncpg.pgproto.pgproto.as_pg_string_and_size
TypeError: expected str, got int

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 545, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\asyncpg\prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\asyncpg\prepared_stmt.py", line 267, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\asyncpg\prepared_stmt.py", line 256, in __do_execute
    return await executor(protocol)
  File "asyncpg\\protocol\\protocol.pyx", line 185, in bind_execute
  File "asyncpg\\protocol\\prepared_stmt.pyx", line 204, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: 9876543210 (expected str, got int)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 9876543210 (expected str, got int)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 109, in app
    response = await f(request)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 387, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\fastapi\routing.py", line 288, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\app\routes\user.py", line 55, in create_user
    existing_user = await session.exec(select(User).where(User.mobile_number == user_in.mobile_number))
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlmodel\ext\asyncio\session.py", line 98, in exec
    result = await greenlet_spawn(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlmodel\orm\session.py", line 83, in exec
    results = super().execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 580, in execute
    self._adapt_connection.await_(
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 558, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 508, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\Users\MS511\Desktop\Customers\Dr_Fazel\Project2\Fazel_Pharma\.venv\lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 792, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 9876543210 (expected str, got int)
[SQL: SELECT "tbl_User".created_at, "tbl_User".updated_at, "tbl_User".telegram_id, "tbl_User".full_name, "tbl_User".national_code, "tbl_User".mobile_number, "tbl_User".address, "tbl_User".is_active, "tbl_User".is_verified, "tbl_User".user_id, "tbl_User".hashed_password, "tbl_User".last_login, "tbl_User".login_attempts, "tbl_User".role_id 
FROM "tbl_User" 
WHERE "tbl_User".mobile_number = $1::VARCHAR]
[parameters: (9876543210,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2025-10-10 17:29:53,670 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 17:29:53,777 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 17:29:53,777 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 17:29:53,777 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 17:29:53,777 - uvicorn.error - INFO - server:94 - Finished server process [17652]
2025-10-10 17:30:26,752 - app - INFO - config:31 - Application startup......................................
2025-10-10 17:30:26,752 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 17:30:33,085 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61321 - "POST /user/ HTTP/1.1" 201
2025-10-10 17:33:38,996 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-10 17:33:39,104 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-10 17:33:39,105 - app - INFO - config:33 - Application shutdown.....................................
2025-10-10 17:33:39,105 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-10 17:33:39,105 - uvicorn.error - INFO - server:94 - Finished server process [15848]
2025-10-10 18:16:04,936 - app - INFO - config:31 - Application startup......................................
2025-10-10 18:16:04,936 - uvicorn.error - INFO - on:62 - Application startup complete.
2025-10-10 18:16:23,970 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:62285 - "POST /login/access-token HTTP/1.1" 200
2025-10-10 18:16:52,051 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:62304 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-10 18:28:44,205 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:62465 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 13:06:29,416 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60321 - "POST /login/access-token HTTP/1.1" 422
2025-10-13 13:43:32,687 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60608 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 13:46:35,939 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:60734 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 13:48:57,998 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61085 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 13:49:30,490 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61104 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-13 13:49:30,494 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61106 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-13 13:50:02,488 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61128 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-13 13:50:02,497 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61130 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-13 13:50:11,716 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61132 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-13 13:50:11,719 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61134 - "GET /users/by-telegram-id/87384626 HTTP/1.1" 404
2025-10-13 14:23:28,392 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:61696 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 14:50:06,854 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:62042 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 14:59:53,509 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:62176 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 15:00:47,088 - uvicorn.access - INFO - httptools_impl:476 - 127.0.0.1:62191 - "POST /login/access-token HTTP/1.1" 200
2025-10-13 15:05:21,477 - uvicorn.error - INFO - server:264 - Shutting down
2025-10-13 15:05:21,585 - uvicorn.error - INFO - on:67 - Waiting for application shutdown.
2025-10-13 15:05:21,588 - app - INFO - config:33 - Application shutdown.....................................
2025-10-13 15:05:21,588 - uvicorn.error - INFO - on:76 - Application shutdown complete.
2025-10-13 15:05:21,589 - uvicorn.error - INFO - server:94 - Finished server process [1072]
